export const defaultSelectFields = [
    "title",
    "path",
    "description",
    "listItemId",
    "identityListItemId",
    "identityListId",
    "identitySiteCollectionId",
    "identityWebId",
    "lastModifiedTime",
    "viewsLifeTime",
    "viewsRecent",
    "owstaxidmetadataalltagsinfo",
    "driveId",
    "author",
    "authorOwsUser",
]